#!/usr/bin/env bash
#
# sync-to-sku.sh — push this fork's BMAD skills and shared tools into a consuming
# project (a "SKU"), then run `bmad doctor` there to reconcile `_bmad/scripts`.
#
# The script lives in the SOURCE repo, not in the consumer: a new SKU copies
# nothing. You `cd` into this fork and point the script at the target.
#
# Two channels, one run:
#   skills/*          ->  <root>/.claude/skills/      (bmad-loop-* excluded)
#   tools/sku-tools/* ->  <root>/Tools/bmad/          (stamped as generated)
#
# Skills present in the SKU but absent from the fork are left alone — that is how
# non-bmad skills and the separately-managed bmad-loop-* skills survive a sync.
#
# Usage:
#   tools/sync-to-sku.sh --root <path-to-sku>
#   tools/sync-to-sku.sh                        # --root defaults to $PWD
#
#   --root <path>   the project to sync into (default: the current directory)
#   --skills-only   mirror skills, skip Tools/bmad
#   --tools-only    mirror Tools/bmad, skip skills and `bmad doctor`
#   --no-doctor     mirror everything, skip `bmad doctor`
#   --dry-run       report what would change, write nothing
#   -h, --help      this text
#
set -euo pipefail

FORK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FORK_SKILLS="$FORK_ROOT/skills"
FORK_TOOLS="$FORK_ROOT/tools/sku-tools"

ROOT=""
DO_SKILLS=1
DO_TOOLS=1
DO_DOCTOR=1
DRY=0

usage() { awk 'NR==1{next} /^set -euo/{exit} /^#/{sub(/^# ?/,""); print}' "$0"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --root)        shift; [ $# -gt 0 ] || { echo "error: --root needs a path" >&2; exit 2; }; ROOT="$1" ;;
    --root=*)      ROOT="${1#--root=}" ;;
    --skills-only) DO_TOOLS=0 ;;
    --tools-only)  DO_SKILLS=0; DO_DOCTOR=0 ;;
    --no-doctor)   DO_DOCTOR=0 ;;
    --dry-run)     DRY=1 ;;
    -h|--help)     usage; exit 0 ;;
    *)             echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

ROOT="${ROOT:-$PWD}"
[ -d "$ROOT" ] || { echo "error: --root is not a directory: $ROOT" >&2; exit 1; }
ROOT="$(cd "$ROOT" && pwd)"

if [ "$ROOT" = "$FORK_ROOT" ]; then
  echo "error: --root is the fork itself ($FORK_ROOT)." >&2
  echo "       Pass the SKU you want to sync into: --root <path-to-sku>" >&2
  exit 1
fi

[ -d "$FORK_SKILLS" ] || { echo "error: fork skills directory not found: $FORK_SKILLS" >&2; exit 1; }

if ! command -v uv >/dev/null 2>&1; then
  echo "error: uv is required (https://docs.astral.sh/uv/)" >&2
  exit 1
fi

VERSION="$(sed -n 's/^version = "\(.*\)"/\1/p' "$FORK_SKILLS/bmad/module-manifest.toml" 2>/dev/null | head -1)"
VERSION="${VERSION:-unknown}"

echo "==> BMAD fork sync"
echo "    fork:    $FORK_ROOT  (version $VERSION)"
echo "    root:    $ROOT"
[ "$DRY" = "1" ] && echo "    MODE:    dry run, nothing is written"

SKILLS_DIR="$ROOT/.claude/skills"
TOOLS_DIR="$ROOT/Tools/bmad"

# ---------------------------------------------------------------- skills ----
copied=0
skipped=0
if [ "$DO_SKILLS" = "1" ]; then
  echo ""
  echo "==> skills  $FORK_SKILLS -> $SKILLS_DIR"
  [ "$DRY" = "1" ] || mkdir -p "$SKILLS_DIR"
  for src in "$FORK_SKILLS"/*/; do
    name="$(basename "$src")"

    # Never touch bmad-loop-* — those come from a different external repo.
    if [[ "$name" == bmad-loop-* ]]; then
      skipped=$((skipped + 1))
      echo "    skip:   $name (bmad-loop-* is managed separately)"
      continue
    fi

    target="$SKILLS_DIR/$name"
    if [ "$DRY" = "0" ]; then
      rm -rf "$target"
      cp -R "$src" "$target"
    fi
    copied=$((copied + 1))
    echo "    synced: $name"
  done
  echo "==> $copied skill(s) synced, $skipped skipped"
fi

# ------------------------------------------------------------- sku tools ----
# Stamp every distributed tool with a provenance header, in the same shape the
# PrototypeFramework uses for its generated Tools/pf/* files: the copy in the SKU
# has a source of truth elsewhere, and an edit made here is silently thrown away
# by the next sync. The stamp is inserted after the shebang and any previous
# stamp is dropped first, so re-running is idempotent.
tools_copied=0
if [ "$DO_TOOLS" = "1" ]; then
  echo ""
  echo "==> tools   $FORK_TOOLS -> $TOOLS_DIR"
  if [ ! -d "$FORK_TOOLS" ]; then
    echo "    note: $FORK_TOOLS does not exist — nothing to distribute"
  else
    [ "$DRY" = "1" ] || mkdir -p "$TOOLS_DIR"
    for src in "$FORK_TOOLS"/*; do
      [ -f "$src" ] || continue
      name="$(basename "$src")"
      dest="$TOOLS_DIR/$name"
      stamp="# GENERATED by BMAD fork $VERSION from tools/sku-tools/$name — do not edit here. Change it in the fork ($FORK_ROOT), then re-run tools/sync-to-sku.sh --root '$ROOT'"
      if [ "$DRY" = "0" ]; then
        awk -v stamp="$stamp" '
          NR==1 && /^#!/ { print; print stamp; next }
          NR<=2 && /^# GENERATED by BMAD fork/ { next }
          { print }
        ' "$src" > "$dest.tmp$$"
        # Keep the source bit-for-bit executable status.
        if [ -x "$src" ]; then chmod +x "$dest.tmp$$"; else chmod -x "$dest.tmp$$"; fi
        mv -f "$dest.tmp$$" "$dest"
      fi
      tools_copied=$((tools_copied + 1))
      echo "    synced: $name"
    done
    echo "==> $tools_copied tool(s) synced"
  fi
fi

# ----------------------------------------------------------------- doctor ----
if [ "$DO_DOCTOR" = "1" ] && [ "$DRY" = "0" ]; then
  BMAD_SKILL="$SKILLS_DIR/bmad"
  if [ ! -f "$BMAD_SKILL/scripts/setup.py" ]; then
    echo "error: bmad skill missing after sync at $BMAD_SKILL" >&2
    exit 1
  fi

  echo ""
  echo "==> Running \`bmad doctor\` to reconcile _bmad/scripts"
  uv run --no-cache "$BMAD_SKILL/scripts/setup.py" \
    --project-root "$ROOT" \
    --skill "$BMAD_SKILL" \
    --doctor
fi

echo ""
echo "==> Sync complete"
